databases:
  - host: localhost
    port: 5432
    user: postgres
    password: postgres
    name: your_database
    delivery: send
    exclude:
      - users.password
      - users.password_hash

  - host: example.com
    port: 5432
    user: admin
    password: admin
    name: eds_db
    delivery: save

directories:
  - ./project/mysite/userdata
  - path: ./project/eds_files
    delivery: send

files:
  - ./project/mysite/main.db
  - path: ./project/config.ini
    delivery: save

dump_dir: ./dumps
files_dir: ./files
schedule: "08:00"

telegram:
  token: 1231231231:6ytrrf236ftyuf7tud32e7tf23yuft
  chat_id: 87632567567
